force-app/main/default/objects/DreamWorks__c/DreamWorks__c.object-meta.xml
<CustomObject>
    <label>Funimation</label>
    <nameField>
        <label>DreamWorks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funimations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DreamWorks__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Articles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DreamWorks__c/fields/Kinikiman__c.field-meta.xml
<CustomField>
    <fullName>Kinikiman__c</fullName>
    <label>Kinikiman</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Articles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>009-1</fullName>
    </customValue>
    <customValue>
        <fullName>009 Re:Cyborg</fullName>
    </customValue>
    <customValue>
        <fullName>18if</fullName>
    </customValue>
    <customValue>
        <fullName>2001 Nights</fullName>
    </customValue>
    <customValue>
        <fullName>91 Days</fullName>
    </customValue>
    <customValue>
        <fullName>Absolute Duo</fullName>
    </customValue>
    <customValue>
        <fullName>ACCA: 13-Territory Inspection Dept.</fullName>
    </customValue>
    <customValue>
        <fullName>Ace Attorney (TV series)</fullName>
    </customValue>
    <customValue>
        <fullName>A Centaur&#39;s Life</fullName>
    </customValue>
    <customValue>
        <fullName>A Certain Magical Index</fullName>
    </customValue>
    <customValue>
        <fullName>A Certain Magical Index: The Movie – The Miracle of Endymion</fullName>
    </customValue>
    <customValue>
        <fullName>A Certain Scientific Railgun</fullName>
    </customValue>
    <customValue>
        <fullName>Aesthetica of a Rogue Hero</fullName>
    </customValue>
    <customValue>
        <fullName>Afro Samurai</fullName>
    </customValue>
    <customValue>
        <fullName>Afro Samurai: Resurrection</fullName>
    </customValue>
    <customValue>
        <fullName>Air (2005 film)</fullName>
    </customValue>
    <customValue>
        <fullName>Air (visual novel)</fullName>
    </customValue>
    <customValue>
        <fullName>Air Gear</fullName>
    </customValue>
    <customValue>
        <fullName>Air Master</fullName>
    </customValue>
    <customValue>
        <fullName>Ai Tenchi Muyo!</fullName>
    </customValue>
    <customValue>
        <fullName>Ai Yori Aoshi</fullName>
    </customValue>
    <customValue>
        <fullName>Akashic Records of Bastard Magic Instructor</fullName>
    </customValue>
    <customValue>
        <fullName>Akiba&#39;s Trip: The Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Akira (1988 film)</fullName>
    </customValue>
    <customValue>
        <fullName>Alderamin on the Sky</fullName>
    </customValue>
    <customValue>
        <fullName>Alice &amp; Zoroku</fullName>
    </customValue>
    <customValue>
        <fullName>Alien vs Ninja</fullName>
    </customValue>
    <customValue>
        <fullName>All Out!!</fullName>
    </customValue>
    <customValue>
        <fullName>And You Thought There Is Never a Girl Online?</fullName>
    </customValue>
    <customValue>
        <fullName>Angel Links</fullName>
    </customValue>
    <masterLabel>Articles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserDetailsController.cls
public class UserDetailsController {
    //creating properties in apex class
    @auraenabled public String DeveloperName {get;set;}
      @auraenabled public String ArticleName {get;set;}	
        @auraenabled public Integer DeveloperAge {get;set;} 
          @auraenabled public List<account> lstofAccount {get;set;}
            @auraenabled public List<DreamWorks__c> lstofFunimation {get;set;}
                
    @auraenabled
    public static UserDetailsController initclass(){
        //creating class instance
       UserDetailsController obj = new UserDetailsController();	
        //set value in class properties
       obj.DeveloperName = 'Rahul';
       obj.DeveloperAge = 27 ;
       obj.ArticleName = 'Funimation';  
       
        //query accounts list for lstofAccount property
       obj.lstOfAccount = [select id, name from account Limit 10];
       obj.lstofFunimation = [select id, name, Category__c, Kinikiman__c from DreamWorks__c Limit 10]; 
        
        //return class instance
       return obj;
      
      }
        
    }